### ISSUE TITLE
Can we customize user-agent for consumer gems

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-sdk-for-ruby#517]
Investigate
- Are we exposing the user-agent customization
- How easy is it to add new user-agent string with each call
- How easy is it to add new user-agent for consuming gems' all calls

**Comment by vishrutshah** [comment]
Here are the answers to the above questions and idea for implementation: 

1. Are we exposing the user-agent customization?
Yes but not streamlined. [HttpOperationRequest](https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest/lib/ms_rest/http_operation_request.rb) contains an attribute names as `user_agent_extended` that can take array of string to be appended as `User-Agent` header for requests. 

2. How easy is it to add new user-agent string with each call?
It can be added through each method call from operation as `custom_headers ` parameter hash and adding a key of `User-Agent` that will be merged in runtime before making a request in the method call [run_promise](https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest/lib/ms_rest/http_operation_request.rb#L80). This doesn't take advantage of `user_agent_extended` parameters. 

3. How easy is it to add new user-agent for consuming gems' all calls?
Every consumer needs to take advantage of the `custom_headers` parameter for each calls to our sdk. It's pain to add header for each call unless customers wants to track how each requests.

**Requirements**
- We should have streamlined option for setting values once per client to be used in each call. 
- Values set on the client should be overridable by each call's `custom_headers` option

**Implementation Proposal** 
Adding `user_agent_extended` on the [ServiceClient](https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest/lib/ms_rest/service_client.rb) will enable each client of the azure_mgmt_* sdks to optionally set the values to be sent to the Azure Services in the part of `User-Agent` headers. 

The sample code would look like below:
```
  require 'azure_mgmt_compute'
  compute_client = ComputeManagementClient.new(@credentials)
  compute_client.subscription_id = 'xxxxxx-xxxxxx-xxxxxx-xxxxx'
  compute_client.user_agent_extended.push('azure_mgmt_compute')
```

Here is the request header would look like:
```
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/<MS_REST_VERSION>/azure_mgmt_compute
      Content-Type:
      - application/json; charset=utf-8
      accept-language:
      - en-US
      x-ms-client-request-id:
      - xxxxxx-xxxxxx-xxxxxx-xxxxx
```

Considering this implementation would open up possibilities to 
1. defaulting `user_agent_extended` to `azure_mgmt_<ARM_NAME>` for Azure.Ruby generator. Will allow us to track telemetry numbers by ARM_NAME as well.
2. allowing consumer gems like fog-azure-rm to set the headers as they create client for each azure_mgmt_* pcakges

Reference: User-Agent specifications from [RFC 1945](https://tools.ietf.org/html/rfc1945#page-46)

@sarangan12, @veronicagg, @jkwon2013, @salameer Any thoughts or feedbacks ?

**Comment by veronicagg** [comment]
Thanks @vishrutshah .
-	In general, I think we should list out the questions and actions we’d like to drive, to determine what telemetry data to collect and how to collect it.
-	Exposing “user_agent_extended” sounds reasonable to allow consumers to include a string in our user-agent. Should we follow the format in the specification product/version pairs?
-	Based on the user_agent specification, we should only be including product/version pairs in the string, will this data be enough to answer our questions (we should state the questions)? Do we need other ways to collect telemetry data?
-	Updating the default user_agent to include the gem name sounds good (and probably version), is there anything else we should/could be including (for the questions we want answers for)? We should not let consumers overwrite our default value, just add to it. Is there anything we should/could capture from the calling environment (OS, ruby version, calling through our client versus not)?

**Comment by vishrutshah** [comment]
Thanks @veronicagg for bringing up these questions. As we discussed offline

- Following are the question that'd like to be answered through telemetry:

```
1. Which of the released azure_mgmt_* gems are used most? 
2. Distributions of how our SDKs are being consumed by third party?
3. What are the platforms and Ruby versions being used most?
4. What the most used client runtimes independent of our SDKs? 
```

- Yes, we should. we are going to follow specification defined at [RFC 1945](https://tools.ietf.org/html/rfc1945#page-46) & [User-Agent Wikipedia](https://en.wikipedia.org/wiki/User_agent)
- That's right, the format would be product/version string separated by spaces. We'll also include other useful inflammations as defined below:

**General Format**: 
```
Mozilla/[version] ([system and browser information]) [platform] ([platform details]) [extensions] 
```
**Ruby Format**: 
```
Ruby/[version] ([OS_platform]) ms_rest/[version] ms_rest_azure/[version] Azure-SDK-For-Ruby [clientpackagename]/[version] [extensions]
```
**Ruby example**: 
```
Ruby/2.2.4 (x86_64-darwin15) ms_rest/0.6.0 ms_rest_azure/0.6.0 Azure-SDK-For-Ruby azure_mgmt_network/0.7.0 fog-azure-rm/0.2.0
```
Here is the request header would look like when call made from network client:
```
    headers:
      User-Agent:
      - Ruby/2.2.4 (x86_64-darwin15) ms_rest/0.6.0 ms_rest_azure/0.6.0 Azure-SDK-For-Ruby
        azure_mgmt_network/0.7.0
      Content-Type:
      - application/json; charset=utf-8
      accept-language:
      - en-US
      x-ms-client-request-id:
      - xxxxxx-xxxxxx-xxxxxx-xxxxx
```

**Comment by vishrutshah** [comment]
Following are the action items to complete this feature:

- [ ] Update ms_rest to expose & extend information supplied to `User-Agent`
- [ ] Update ms_rest_azure to expose & extend information supplied to `User-Agent`
- [ ] Release new version of ms_rest and ms_rest_azure
- [ ] Update Ruby & Azure.Ruby generators in AutoRest to leverage this functionality for azure_mgmt_* sdks
- [ ] Regenerate all azure_mgmt_* sdks to use latest generator and runtimes
- [ ] Update & encourage external consumers of azure_mgmt_* gems to leverage this feature
- [ ] Analyse & Act based on the rich telemetry support

Feel free to update action items in case i missed any steps. 

Thanks,
